// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['forms.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufc_finite_element element_416fe89e298e913bae63411a0763e13b8a95f387;

extern ufc_finite_element element_52a3d897ddb1cd2662ce11f971bc6278270a56f4;

extern ufc_finite_element element_ac8daf68e2e0e4a0d2f937a825185b2403d050aa;

extern ufc_dofmap dofmap_416fe89e298e913bae63411a0763e13b8a95f387;

extern ufc_dofmap dofmap_52a3d897ddb1cd2662ce11f971bc6278270a56f4;

extern ufc_dofmap dofmap_ac8daf68e2e0e4a0d2f937a825185b2403d050aa;

extern ufc_integral integral_eb582c5a9cd92e9ba8da568bce83fed5abc79f6e;

extern ufc_integral integral_3197c45ce5a88cda186707b2d1a09f269e405c14;

extern ufc_form form_f3f0c33aa65e26247998a8bdb618a56f526180d6;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_forms_a;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_forms_a(const char* function_name);

extern ufc_form form_92b312a26f6ae184aee942c16c6e1e84139d10fd;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_forms_L;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_forms_L(const char* function_name);

#ifdef __cplusplus
}
#endif
