// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['forms.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

typedef double ufc_scalar_t;
#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufc_finite_element element_23c31b61d045664e6db105a2c9c3838bf3612ff9;

extern ufc_finite_element element_a9e8e7596b732d9bbfba031bddc043806ab90148;

extern ufc_finite_element element_9846521eb4e2336f35c4d59f548f622857f5d745;

extern ufc_dofmap dofmap_23c31b61d045664e6db105a2c9c3838bf3612ff9;

extern ufc_dofmap dofmap_a9e8e7596b732d9bbfba031bddc043806ab90148;

extern ufc_dofmap dofmap_9846521eb4e2336f35c4d59f548f622857f5d745;

extern ufc_integral integral_1758fdd40c7c43508cc9d8ddb162132ee5011c7c;

extern ufc_integral integral_bb200653c28ae2e918f8634c88e2f45357742b38;

extern ufc_integral integral_d882f99b9e5bcbffe3f9c112d459d1bcfd0c5161;

extern ufc_integral integral_978dc8ee37187e5500ea5f11edb90031501828f7;

extern ufc_integral integral_aa876e402c78ded7641177dcbc75695737f0acd9;

extern ufc_form form_cb5f09f40f599bffa54f93b427616a6defefe4a0;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_forms_a;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_forms_a(const char* function_name);

extern ufc_form form_62934eae624c2ccba4711b3560d0440d49f31712;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_forms_L;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_forms_L(const char* function_name);

#ifdef __cplusplus
}
#endif
