// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['forms.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufc_finite_element element_0e38e3c5cc256e0fdffd1c92e71f8c34b307d320;

extern ufc_finite_element element_a6e3e0cd38b5fe106365a8578b981e54950d9f2b;

extern ufc_finite_element element_9d6ce2fe3901e74605eea98aa23296f9d9c28b32;

extern ufc_dofmap dofmap_0e38e3c5cc256e0fdffd1c92e71f8c34b307d320;

extern ufc_dofmap dofmap_a6e3e0cd38b5fe106365a8578b981e54950d9f2b;

extern ufc_dofmap dofmap_9d6ce2fe3901e74605eea98aa23296f9d9c28b32;

extern ufc_integral integral_f0fd279d1fafc146d3e132a7079cddf8af8bcadc;

extern ufc_integral integral_0f7465472927146bdcdf5b2d3efe57812e2c5ced;

extern ufc_integral integral_6bbf024a58ee8ad9d59d61f8741a050e4755cf82;

extern ufc_integral integral_3a4696ed743178b66ac3c7b30b35f9989994dc18;

extern ufc_integral integral_433e0250713a389892977f17d5b0a096efd708aa;

extern ufc_form form_354dc81f7a85caed455170591b69273cad287602;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_forms_a;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_forms_a(const char* function_name);

extern ufc_form form_26066afd0b42297891a965ce626061646efa3a87;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_forms_L;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_forms_L(const char* function_name);

#ifdef __cplusplus
}
#endif
