// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['forms.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#include <math.h>
#include <stdalign.h>
#include <stdlib.h>
#include <string.h>
#include <ufc.h>

// Code for element element_ee7755fb9192d85e9bbabdfa958a19575d037fcb





ufc_finite_element element_ee7755fb9192d85e9bbabdfa958a19575d037fcb =
{
  .signature = "FiniteElement('Q', quadrilateral, 1)",
  .cell_shape = quadrilateral,
  .element_type = ufc_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 4,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 1,
  .block_size = 1,
  .family = "Q",
  .basix_family = 1,
  .basix_cell = 4,
  .discontinuous = false,
  .lagrange_variant = 1,
  .num_sub_elements = 0,
  .sub_elements = NULL
};

// End of code for element element_ee7755fb9192d85e9bbabdfa958a19575d037fcb

// Code for element element_c7ad61b539c6dd97225dd4dda3c3916557532058

int value_shape_element_c7ad61b539c6dd97225dd4dda3c3916557532058[1] = { 2 };
int reference_value_shape_element_c7ad61b539c6dd97225dd4dda3c3916557532058[1] = { 2 };
ufc_finite_element* sub_elements_element_c7ad61b539c6dd97225dd4dda3c3916557532058[2] = { &element_ee7755fb9192d85e9bbabdfa958a19575d037fcb, &element_ee7755fb9192d85e9bbabdfa958a19575d037fcb };

ufc_finite_element element_c7ad61b539c6dd97225dd4dda3c3916557532058 =
{
  .signature = "VectorElement(FiniteElement('Q', quadrilateral, 1), dim=2)",
  .cell_shape = quadrilateral,
  .element_type = ufc_blocked_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 8,
  .value_rank = 1,
  .value_shape = value_shape_element_c7ad61b539c6dd97225dd4dda3c3916557532058,
  .value_size = 2,
  .reference_value_rank = 1,
  .reference_value_shape = reference_value_shape_element_c7ad61b539c6dd97225dd4dda3c3916557532058,
  .reference_value_size = 2,
  .degree = 1,
  .block_size = 2,
  .family = "Q",
  .basix_family = 1,
  .basix_cell = 4,
  .discontinuous = false,
  .lagrange_variant = 1,
  .num_sub_elements = 2,
  .sub_elements = sub_elements_element_c7ad61b539c6dd97225dd4dda3c3916557532058
};

// End of code for element element_c7ad61b539c6dd97225dd4dda3c3916557532058

// Code for element element_a5e99f850cd469e7d420d8a3568af11c4cdb6db9





ufc_finite_element element_a5e99f850cd469e7d420d8a3568af11c4cdb6db9 =
{
  .signature = "FiniteElement('Q', quadrilateral, 4, variant='gll')",
  .cell_shape = quadrilateral,
  .element_type = ufc_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 25,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 4,
  .block_size = 1,
  .family = "Q",
  .basix_family = 1,
  .basix_cell = 4,
  .discontinuous = false,
  .lagrange_variant = 1,
  .num_sub_elements = 0,
  .sub_elements = NULL
};

// End of code for element element_a5e99f850cd469e7d420d8a3568af11c4cdb6db9

// Code for dofmap dofmap_ee7755fb9192d85e9bbabdfa958a19575d037fcb



void tabulate_entity_dofs_dofmap_ee7755fb9192d85e9bbabdfa958a19575d037fcb(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
}
}

void tabulate_entity_closure_dofs_dofmap_ee7755fb9192d85e9bbabdfa958a19575d037fcb(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
case 1:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        dofs[1] = 1;
        break;
    case 1:
        dofs[0] = 0;
        dofs[1] = 2;
        break;
    case 2:
        dofs[0] = 1;
        dofs[1] = 3;
        break;
    case 3:
        dofs[0] = 2;
        dofs[1] = 3;
        break;
    }
    break;
case 2:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        dofs[1] = 1;
        dofs[2] = 2;
        dofs[3] = 3;
        break;
    }
    break;
}
}

int num_entity_dofs_dofmap_ee7755fb9192d85e9bbabdfa958a19575d037fcb[4] = { 1, 0, 0, 0 };

int num_entity_closure_dofs_dofmap_ee7755fb9192d85e9bbabdfa958a19575d037fcb[4] = { 1, 2, 4, 0 };

ufc_dofmap dofmap_ee7755fb9192d85e9bbabdfa958a19575d037fcb =
{
  .signature = "FFCx dofmap for FiniteElement('Q', quadrilateral, 1)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 4,
  .block_size = 1,
  .num_entity_dofs = num_entity_dofs_dofmap_ee7755fb9192d85e9bbabdfa958a19575d037fcb,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_ee7755fb9192d85e9bbabdfa958a19575d037fcb,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_ee7755fb9192d85e9bbabdfa958a19575d037fcb,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_ee7755fb9192d85e9bbabdfa958a19575d037fcb,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_ee7755fb9192d85e9bbabdfa958a19575d037fcb

// Code for dofmap dofmap_c7ad61b539c6dd97225dd4dda3c3916557532058

ufc_dofmap* sub_dofmaps_dofmap_c7ad61b539c6dd97225dd4dda3c3916557532058[2] = { &dofmap_ee7755fb9192d85e9bbabdfa958a19575d037fcb, &dofmap_ee7755fb9192d85e9bbabdfa958a19575d037fcb };

void tabulate_entity_dofs_dofmap_c7ad61b539c6dd97225dd4dda3c3916557532058(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
}
}

void tabulate_entity_closure_dofs_dofmap_c7ad61b539c6dd97225dd4dda3c3916557532058(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
case 1:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        dofs[1] = 1;
        break;
    case 1:
        dofs[0] = 0;
        dofs[1] = 2;
        break;
    case 2:
        dofs[0] = 1;
        dofs[1] = 3;
        break;
    case 3:
        dofs[0] = 2;
        dofs[1] = 3;
        break;
    }
    break;
case 2:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        dofs[1] = 1;
        dofs[2] = 2;
        dofs[3] = 3;
        break;
    }
    break;
}
}

int num_entity_dofs_dofmap_c7ad61b539c6dd97225dd4dda3c3916557532058[4] = { 1, 0, 0, 0 };

int num_entity_closure_dofs_dofmap_c7ad61b539c6dd97225dd4dda3c3916557532058[4] = { 1, 2, 4, 0 };

ufc_dofmap dofmap_c7ad61b539c6dd97225dd4dda3c3916557532058 =
{
  .signature = "FFCx dofmap for VectorElement(FiniteElement('Q', quadrilateral, 1), dim=2)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 4,
  .block_size = 2,
  .num_entity_dofs = num_entity_dofs_dofmap_c7ad61b539c6dd97225dd4dda3c3916557532058,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_c7ad61b539c6dd97225dd4dda3c3916557532058,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_c7ad61b539c6dd97225dd4dda3c3916557532058,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_c7ad61b539c6dd97225dd4dda3c3916557532058,
  .num_sub_dofmaps = 2,
  .sub_dofmaps = sub_dofmaps_dofmap_c7ad61b539c6dd97225dd4dda3c3916557532058
};

// End of code for dofmap dofmap_c7ad61b539c6dd97225dd4dda3c3916557532058

// Code for dofmap dofmap_a5e99f850cd469e7d420d8a3568af11c4cdb6db9



void tabulate_entity_dofs_dofmap_a5e99f850cd469e7d420d8a3568af11c4cdb6db9(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
case 1:
    switch (i)
    {
    case 0:
        dofs[0] = 4;
        dofs[1] = 5;
        dofs[2] = 6;
        break;
    case 1:
        dofs[0] = 7;
        dofs[1] = 8;
        dofs[2] = 9;
        break;
    case 2:
        dofs[0] = 10;
        dofs[1] = 11;
        dofs[2] = 12;
        break;
    case 3:
        dofs[0] = 13;
        dofs[1] = 14;
        dofs[2] = 15;
        break;
    }
    break;
case 2:
    switch (i)
    {
    case 0:
        dofs[0] = 16;
        dofs[1] = 17;
        dofs[2] = 18;
        dofs[3] = 19;
        dofs[4] = 20;
        dofs[5] = 21;
        dofs[6] = 22;
        dofs[7] = 23;
        dofs[8] = 24;
        break;
    }
    break;
}
}

void tabulate_entity_closure_dofs_dofmap_a5e99f850cd469e7d420d8a3568af11c4cdb6db9(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
case 1:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        dofs[1] = 1;
        dofs[2] = 4;
        dofs[3] = 5;
        dofs[4] = 6;
        break;
    case 1:
        dofs[0] = 0;
        dofs[1] = 2;
        dofs[2] = 7;
        dofs[3] = 8;
        dofs[4] = 9;
        break;
    case 2:
        dofs[0] = 1;
        dofs[1] = 3;
        dofs[2] = 10;
        dofs[3] = 11;
        dofs[4] = 12;
        break;
    case 3:
        dofs[0] = 2;
        dofs[1] = 3;
        dofs[2] = 13;
        dofs[3] = 14;
        dofs[4] = 15;
        break;
    }
    break;
case 2:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        dofs[1] = 1;
        dofs[2] = 2;
        dofs[3] = 3;
        dofs[4] = 4;
        dofs[5] = 5;
        dofs[6] = 6;
        dofs[7] = 7;
        dofs[8] = 8;
        dofs[9] = 9;
        dofs[10] = 10;
        dofs[11] = 11;
        dofs[12] = 12;
        dofs[13] = 13;
        dofs[14] = 14;
        dofs[15] = 15;
        dofs[16] = 16;
        dofs[17] = 17;
        dofs[18] = 18;
        dofs[19] = 19;
        dofs[20] = 20;
        dofs[21] = 21;
        dofs[22] = 22;
        dofs[23] = 23;
        dofs[24] = 24;
        break;
    }
    break;
}
}

int num_entity_dofs_dofmap_a5e99f850cd469e7d420d8a3568af11c4cdb6db9[4] = { 1, 3, 9, 0 };

int num_entity_closure_dofs_dofmap_a5e99f850cd469e7d420d8a3568af11c4cdb6db9[4] = { 1, 5, 25, 0 };

ufc_dofmap dofmap_a5e99f850cd469e7d420d8a3568af11c4cdb6db9 =
{
  .signature = "FFCx dofmap for FiniteElement('Q', quadrilateral, 4, variant='gll')",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 25,
  .block_size = 1,
  .num_entity_dofs = num_entity_dofs_dofmap_a5e99f850cd469e7d420d8a3568af11c4cdb6db9,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_a5e99f850cd469e7d420d8a3568af11c4cdb6db9,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_a5e99f850cd469e7d420d8a3568af11c4cdb6db9,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_a5e99f850cd469e7d420d8a3568af11c4cdb6db9,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_a5e99f850cd469e7d420d8a3568af11c4cdb6db9

// Code for integral integral_4be71c5d2400b36f7fc7742798968f463c6b32c1

void tabulate_tensor_integral_4be71c5d2400b36f7fc7742798968f463c6b32c1(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
    // Quadrature rules
    static const double weights_ba5[5] = { 0.05000000000000004, 0.2722222222222223, 0.3555555555555555, 0.272222222222222, 0.05000000000000004 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [permutation][entities][points][dofs]
    static const double FE4_C0_D01_F_Qba5[2][4][5][4] =
        { { { { -1.0, 0.0, 1.0, 0.0 },
              { -0.8273268353539882, -0.1726731646460115, 0.8273268353539884, 0.1726731646460114 },
              { -0.4999999999999999, -0.4999999999999999, 0.5, 0.5 },
              { -0.1726731646460116, -0.8273268353539884, 0.1726731646460115, 0.8273268353539887 },
              { 0.0, -1.0, 0.0, 1.0 } },
            { { -1.0, 0.0, 1.0, 0.0 },
              { -1.0, 0.0, 1.0, 0.0 },
              { -1.0, 0.0, 1.0, 0.0 },
              { -1.0, 0.0, 1.0, 0.0 },
              { -1.0, 0.0, 1.0, 0.0 } },
            { { 0.0, -1.0, 0.0, 1.0 },
              { 0.0, -1.0, 0.0, 1.0 },
              { 0.0, -1.0, 0.0, 1.0 },
              { 0.0, -1.0, 0.0, 1.0 },
              { 0.0, -1.0, 0.0, 1.0 } },
            { { -1.0, 0.0, 1.0, 0.0 },
              { -0.8273268353539882, -0.1726731646460115, 0.8273268353539884, 0.1726731646460114 },
              { -0.4999999999999999, -0.4999999999999999, 0.5, 0.5 },
              { -0.1726731646460116, -0.8273268353539884, 0.1726731646460115, 0.8273268353539887 },
              { 0.0, -1.0, 0.0, 1.0 } } },
          { { { 0.0, -1.0, 0.0, 1.0 },
              { -0.1726731646460116, -0.8273268353539884, 0.1726731646460115, 0.8273268353539887 },
              { -0.4999999999999999, -0.4999999999999999, 0.5, 0.5 },
              { -0.8273268353539882, -0.1726731646460115, 0.8273268353539884, 0.1726731646460114 },
              { -1.0, 0.0, 1.0, 0.0 } },
            { { -1.0, 0.0, 1.0, 0.0 },
              { -1.0, 0.0, 1.0, 0.0 },
              { -1.0, 0.0, 1.0, 0.0 },
              { -1.0, 0.0, 1.0, 0.0 },
              { -1.0, 0.0, 1.0, 0.0 } },
            { { 0.0, -1.0, 0.0, 1.0 },
              { 0.0, -1.0, 0.0, 1.0 },
              { 0.0, -1.0, 0.0, 1.0 },
              { 0.0, -1.0, 0.0, 1.0 },
              { 0.0, -1.0, 0.0, 1.0 } },
            { { 0.0, -1.0, 0.0, 1.0 },
              { -0.1726731646460116, -0.8273268353539884, 0.1726731646460115, 0.8273268353539887 },
              { -0.4999999999999999, -0.4999999999999999, 0.5, 0.5 },
              { -0.8273268353539882, -0.1726731646460115, 0.8273268353539884, 0.1726731646460114 },
              { -1.0, 0.0, 1.0, 0.0 } } } };
    static const double FE4_C0_D10_F_Qba5[2][4][5][4] =
        { { { { -1.0, 1.0, 0.0, 0.0 },
              { -1.0, 1.0, 0.0, 0.0 },
              { -1.0, 1.0, 0.0, 0.0 },
              { -1.0, 1.0, 0.0, 0.0 },
              { -1.0, 1.0, 0.0, 0.0 } },
            { { -1.0, 1.0, 0.0, 0.0 },
              { -0.8273268353539882, 0.8273268353539884, -0.1726731646460115, 0.1726731646460114 },
              { -0.4999999999999998, 0.5, -0.4999999999999999, 0.5 },
              { -0.1726731646460115, 0.1726731646460115, -0.8273268353539884, 0.8273268353539887 },
              { 0.0, 0.0, -1.0, 1.0 } },
            { { -1.0, 1.0, 0.0, 0.0 },
              { -0.8273268353539882, 0.8273268353539884, -0.1726731646460115, 0.1726731646460114 },
              { -0.4999999999999998, 0.5, -0.4999999999999999, 0.5 },
              { -0.1726731646460115, 0.1726731646460115, -0.8273268353539884, 0.8273268353539887 },
              { 0.0, 0.0, -1.0, 1.0 } },
            { { 0.0, 0.0, -1.0, 1.0 },
              { 0.0, 0.0, -1.0, 1.0 },
              { 0.0, 0.0, -1.0, 1.0 },
              { 0.0, 0.0, -1.0, 1.0 },
              { 0.0, 0.0, -1.0, 1.0 } } },
          { { { -1.0, 1.0, 0.0, 0.0 },
              { -1.0, 1.0, 0.0, 0.0 },
              { -1.0, 1.0, 0.0, 0.0 },
              { -1.0, 1.0, 0.0, 0.0 },
              { -1.0, 1.0, 0.0, 0.0 } },
            { { 0.0, 0.0, -1.0, 1.0 },
              { -0.1726731646460115, 0.1726731646460115, -0.8273268353539884, 0.8273268353539887 },
              { -0.4999999999999998, 0.5, -0.4999999999999999, 0.5 },
              { -0.8273268353539882, 0.8273268353539884, -0.1726731646460115, 0.1726731646460114 },
              { -1.0, 1.0, 0.0, 0.0 } },
            { { 0.0, 0.0, -1.0, 1.0 },
              { -0.1726731646460115, 0.1726731646460115, -0.8273268353539884, 0.8273268353539887 },
              { -0.4999999999999998, 0.5, -0.4999999999999999, 0.5 },
              { -0.8273268353539882, 0.8273268353539884, -0.1726731646460115, 0.1726731646460114 },
              { -1.0, 1.0, 0.0, 0.0 } },
            { { 0.0, 0.0, -1.0, 1.0 },
              { 0.0, 0.0, -1.0, 1.0 },
              { 0.0, 0.0, -1.0, 1.0 },
              { 0.0, 0.0, -1.0, 1.0 },
              { 0.0, 0.0, -1.0, 1.0 } } } };
    static const double FE6_C0_F_Qba5[2][4][5][25] =
        { { { { 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
            { { 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
            { { 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
            { { 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } } },
          { { { 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
            { { 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
            { { 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
            { { 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } } } };
    static const double quadrilateral_reference_facet_jacobian[4][2][1] =
        { { { 1.0 },
            { 0.0 } },
          { { 0.0 },
            { 1.0 } },
          { { 0.0 },
            { 1.0 } },
          { { 1.0 },
            { 0.0 } } };
    for (int iq = 0; iq < 5; ++iq)
    {
        // Quadrature loop body setup for quadrature rule ba5
        // Varying computations for quadrature rule ba5
        double w1 = 0.0;
        const double J_c0 = coordinate_dofs[0] * FE4_C0_D10_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][0] + coordinate_dofs[3] * FE4_C0_D10_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][1] + coordinate_dofs[6] * FE4_C0_D10_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][2] + coordinate_dofs[9] * FE4_C0_D10_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][3];
        const double J_c1 = coordinate_dofs[0] * FE4_C0_D01_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][0] + coordinate_dofs[3] * FE4_C0_D01_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][1] + coordinate_dofs[6] * FE4_C0_D01_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][2] + coordinate_dofs[9] * FE4_C0_D01_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][3];
        const double J_c2 = coordinate_dofs[1] * FE4_C0_D10_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][0] + coordinate_dofs[4] * FE4_C0_D10_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][1] + coordinate_dofs[7] * FE4_C0_D10_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][2] + coordinate_dofs[10] * FE4_C0_D10_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][3];
        const double J_c3 = coordinate_dofs[1] * FE4_C0_D01_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][0] + coordinate_dofs[4] * FE4_C0_D01_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][1] + coordinate_dofs[7] * FE4_C0_D01_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][2] + coordinate_dofs[10] * FE4_C0_D01_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][3];
        for (int ic = 0; ic < 25; ++ic)
            w1 += w[25 + ic] * FE6_C0_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][ic];
        double sv_ba5[12];
        sv_ba5[0] = pow(c[0], 2) * w1;
        sv_ba5[1] = J_c0 * quadrilateral_reference_facet_jacobian[entity_local_index[0]][0][0];
        sv_ba5[2] = J_c1 * quadrilateral_reference_facet_jacobian[entity_local_index[0]][1][0];
        sv_ba5[3] = sv_ba5[1] + sv_ba5[2];
        sv_ba5[4] = sv_ba5[3] * sv_ba5[3];
        sv_ba5[5] = quadrilateral_reference_facet_jacobian[entity_local_index[0]][0][0] * J_c2;
        sv_ba5[6] = quadrilateral_reference_facet_jacobian[entity_local_index[0]][1][0] * J_c3;
        sv_ba5[7] = sv_ba5[5] + sv_ba5[6];
        sv_ba5[8] = sv_ba5[7] * sv_ba5[7];
        sv_ba5[9] = sv_ba5[4] + sv_ba5[8];
        sv_ba5[10] = sqrt(sv_ba5[9]);
        sv_ba5[11] = sv_ba5[0] * sv_ba5[10];
        const double fw0 = sv_ba5[11] * weights_ba5[iq];
        for (int i = 0; i < 25; ++i)
            A[i] += fw0 * FE6_C0_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][i];
    }
}

bool enabled_coefficients_integral_4be71c5d2400b36f7fc7742798968f463c6b32c1[2] = { false, false };

ufc_integral integral_4be71c5d2400b36f7fc7742798968f463c6b32c1 =
{
  .enabled_coefficients = enabled_coefficients_integral_4be71c5d2400b36f7fc7742798968f463c6b32c1,
  .tabulate_tensor_float64 = tabulate_tensor_integral_4be71c5d2400b36f7fc7742798968f463c6b32c1,
  .needs_facet_permutations = false,
  .coordinate_element = &element_c7ad61b539c6dd97225dd4dda3c3916557532058,
};

// End of code for integral integral_4be71c5d2400b36f7fc7742798968f463c6b32c1

// Code for integral integral_34c5363dbbbf18f54bd4da429b90a70aeb429e7f

void tabulate_tensor_integral_34c5363dbbbf18f54bd4da429b90a70aeb429e7f(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
    // Quadrature rules
    static const double weights_ba5[5] = { 0.05000000000000004, 0.2722222222222223, 0.3555555555555555, 0.272222222222222, 0.05000000000000004 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [permutation][entities][points][dofs]
    static const double FE4_C0_D01_F_Qba5[2][4][5][4] =
        { { { { -1.0, 0.0, 1.0, 0.0 },
              { -0.8273268353539882, -0.1726731646460115, 0.8273268353539884, 0.1726731646460114 },
              { -0.4999999999999999, -0.4999999999999999, 0.5, 0.5 },
              { -0.1726731646460116, -0.8273268353539884, 0.1726731646460115, 0.8273268353539887 },
              { 0.0, -1.0, 0.0, 1.0 } },
            { { -1.0, 0.0, 1.0, 0.0 },
              { -1.0, 0.0, 1.0, 0.0 },
              { -1.0, 0.0, 1.0, 0.0 },
              { -1.0, 0.0, 1.0, 0.0 },
              { -1.0, 0.0, 1.0, 0.0 } },
            { { 0.0, -1.0, 0.0, 1.0 },
              { 0.0, -1.0, 0.0, 1.0 },
              { 0.0, -1.0, 0.0, 1.0 },
              { 0.0, -1.0, 0.0, 1.0 },
              { 0.0, -1.0, 0.0, 1.0 } },
            { { -1.0, 0.0, 1.0, 0.0 },
              { -0.8273268353539882, -0.1726731646460115, 0.8273268353539884, 0.1726731646460114 },
              { -0.4999999999999999, -0.4999999999999999, 0.5, 0.5 },
              { -0.1726731646460116, -0.8273268353539884, 0.1726731646460115, 0.8273268353539887 },
              { 0.0, -1.0, 0.0, 1.0 } } },
          { { { 0.0, -1.0, 0.0, 1.0 },
              { -0.1726731646460116, -0.8273268353539884, 0.1726731646460115, 0.8273268353539887 },
              { -0.4999999999999999, -0.4999999999999999, 0.5, 0.5 },
              { -0.8273268353539882, -0.1726731646460115, 0.8273268353539884, 0.1726731646460114 },
              { -1.0, 0.0, 1.0, 0.0 } },
            { { -1.0, 0.0, 1.0, 0.0 },
              { -1.0, 0.0, 1.0, 0.0 },
              { -1.0, 0.0, 1.0, 0.0 },
              { -1.0, 0.0, 1.0, 0.0 },
              { -1.0, 0.0, 1.0, 0.0 } },
            { { 0.0, -1.0, 0.0, 1.0 },
              { 0.0, -1.0, 0.0, 1.0 },
              { 0.0, -1.0, 0.0, 1.0 },
              { 0.0, -1.0, 0.0, 1.0 },
              { 0.0, -1.0, 0.0, 1.0 } },
            { { 0.0, -1.0, 0.0, 1.0 },
              { -0.1726731646460116, -0.8273268353539884, 0.1726731646460115, 0.8273268353539887 },
              { -0.4999999999999999, -0.4999999999999999, 0.5, 0.5 },
              { -0.8273268353539882, -0.1726731646460115, 0.8273268353539884, 0.1726731646460114 },
              { -1.0, 0.0, 1.0, 0.0 } } } };
    static const double FE4_C0_D10_F_Qba5[2][4][5][4] =
        { { { { -1.0, 1.0, 0.0, 0.0 },
              { -1.0, 1.0, 0.0, 0.0 },
              { -1.0, 1.0, 0.0, 0.0 },
              { -1.0, 1.0, 0.0, 0.0 },
              { -1.0, 1.0, 0.0, 0.0 } },
            { { -1.0, 1.0, 0.0, 0.0 },
              { -0.8273268353539882, 0.8273268353539884, -0.1726731646460115, 0.1726731646460114 },
              { -0.4999999999999998, 0.5, -0.4999999999999999, 0.5 },
              { -0.1726731646460115, 0.1726731646460115, -0.8273268353539884, 0.8273268353539887 },
              { 0.0, 0.0, -1.0, 1.0 } },
            { { -1.0, 1.0, 0.0, 0.0 },
              { -0.8273268353539882, 0.8273268353539884, -0.1726731646460115, 0.1726731646460114 },
              { -0.4999999999999998, 0.5, -0.4999999999999999, 0.5 },
              { -0.1726731646460115, 0.1726731646460115, -0.8273268353539884, 0.8273268353539887 },
              { 0.0, 0.0, -1.0, 1.0 } },
            { { 0.0, 0.0, -1.0, 1.0 },
              { 0.0, 0.0, -1.0, 1.0 },
              { 0.0, 0.0, -1.0, 1.0 },
              { 0.0, 0.0, -1.0, 1.0 },
              { 0.0, 0.0, -1.0, 1.0 } } },
          { { { -1.0, 1.0, 0.0, 0.0 },
              { -1.0, 1.0, 0.0, 0.0 },
              { -1.0, 1.0, 0.0, 0.0 },
              { -1.0, 1.0, 0.0, 0.0 },
              { -1.0, 1.0, 0.0, 0.0 } },
            { { 0.0, 0.0, -1.0, 1.0 },
              { -0.1726731646460115, 0.1726731646460115, -0.8273268353539884, 0.8273268353539887 },
              { -0.4999999999999998, 0.5, -0.4999999999999999, 0.5 },
              { -0.8273268353539882, 0.8273268353539884, -0.1726731646460115, 0.1726731646460114 },
              { -1.0, 1.0, 0.0, 0.0 } },
            { { 0.0, 0.0, -1.0, 1.0 },
              { -0.1726731646460115, 0.1726731646460115, -0.8273268353539884, 0.8273268353539887 },
              { -0.4999999999999998, 0.5, -0.4999999999999999, 0.5 },
              { -0.8273268353539882, 0.8273268353539884, -0.1726731646460115, 0.1726731646460114 },
              { -1.0, 1.0, 0.0, 0.0 } },
            { { 0.0, 0.0, -1.0, 1.0 },
              { 0.0, 0.0, -1.0, 1.0 },
              { 0.0, 0.0, -1.0, 1.0 },
              { 0.0, 0.0, -1.0, 1.0 },
              { 0.0, 0.0, -1.0, 1.0 } } } };
    static const double FE6_C0_F_Qba5[2][4][5][25] =
        { { { { 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
            { { 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
            { { 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
            { { 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } } },
          { { { 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
            { { 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
            { { 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
            { { 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } } } };
    static const double quadrilateral_reference_facet_jacobian[4][2][1] =
        { { { 1.0 },
            { 0.0 } },
          { { 0.0 },
            { 1.0 } },
          { { 0.0 },
            { 1.0 } },
          { { 1.0 },
            { 0.0 } } };
    for (int iq = 0; iq < 5; ++iq)
    {
        // Quadrature loop body setup for quadrature rule ba5
        // Varying computations for quadrature rule ba5
        double w0 = 0.0;
        const double J_c0 = coordinate_dofs[0] * FE4_C0_D10_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][0] + coordinate_dofs[3] * FE4_C0_D10_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][1] + coordinate_dofs[6] * FE4_C0_D10_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][2] + coordinate_dofs[9] * FE4_C0_D10_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][3];
        const double J_c1 = coordinate_dofs[0] * FE4_C0_D01_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][0] + coordinate_dofs[3] * FE4_C0_D01_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][1] + coordinate_dofs[6] * FE4_C0_D01_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][2] + coordinate_dofs[9] * FE4_C0_D01_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][3];
        const double J_c2 = coordinate_dofs[1] * FE4_C0_D10_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][0] + coordinate_dofs[4] * FE4_C0_D10_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][1] + coordinate_dofs[7] * FE4_C0_D10_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][2] + coordinate_dofs[10] * FE4_C0_D10_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][3];
        const double J_c3 = coordinate_dofs[1] * FE4_C0_D01_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][0] + coordinate_dofs[4] * FE4_C0_D01_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][1] + coordinate_dofs[7] * FE4_C0_D01_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][2] + coordinate_dofs[10] * FE4_C0_D01_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][3];
        for (int ic = 0; ic < 25; ++ic)
            w0 += w[ic] * FE6_C0_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][ic];
        double sv_ba5[13];
        sv_ba5[0] = (1 / c[0]) * w0;
        sv_ba5[1] = (-1 * sv_ba5[0]) * pow(c[0], 2);
        sv_ba5[2] = J_c0 * quadrilateral_reference_facet_jacobian[entity_local_index[0]][0][0];
        sv_ba5[3] = J_c1 * quadrilateral_reference_facet_jacobian[entity_local_index[0]][1][0];
        sv_ba5[4] = sv_ba5[2] + sv_ba5[3];
        sv_ba5[5] = sv_ba5[4] * sv_ba5[4];
        sv_ba5[6] = quadrilateral_reference_facet_jacobian[entity_local_index[0]][0][0] * J_c2;
        sv_ba5[7] = quadrilateral_reference_facet_jacobian[entity_local_index[0]][1][0] * J_c3;
        sv_ba5[8] = sv_ba5[6] + sv_ba5[7];
        sv_ba5[9] = sv_ba5[8] * sv_ba5[8];
        sv_ba5[10] = sv_ba5[5] + sv_ba5[9];
        sv_ba5[11] = sqrt(sv_ba5[10]);
        sv_ba5[12] = sv_ba5[1] * sv_ba5[11];
        const double fw0 = sv_ba5[12] * weights_ba5[iq];
        for (int i = 0; i < 25; ++i)
            A[i] += fw0 * FE6_C0_F_Qba5[quadrature_permutation[0]][entity_local_index[0]][iq][i];
    }
}

bool enabled_coefficients_integral_34c5363dbbbf18f54bd4da429b90a70aeb429e7f[2] = { false, false };

ufc_integral integral_34c5363dbbbf18f54bd4da429b90a70aeb429e7f =
{
  .enabled_coefficients = enabled_coefficients_integral_34c5363dbbbf18f54bd4da429b90a70aeb429e7f,
  .tabulate_tensor_float64 = tabulate_tensor_integral_34c5363dbbbf18f54bd4da429b90a70aeb429e7f,
  .needs_facet_permutations = false,
  .coordinate_element = &element_c7ad61b539c6dd97225dd4dda3c3916557532058,
};

// End of code for integral integral_34c5363dbbbf18f54bd4da429b90a70aeb429e7f

// Code for form form_fb78e22a9a6073a61b5fb762f339e95a5b634838

int original_coefficient_position_form_fb78e22a9a6073a61b5fb762f339e95a5b634838[2] = { 0, 1 };
ufc_dofmap* dofmaps_form_fb78e22a9a6073a61b5fb762f339e95a5b634838[3] = { &dofmap_a5e99f850cd469e7d420d8a3568af11c4cdb6db9, &dofmap_a5e99f850cd469e7d420d8a3568af11c4cdb6db9, &dofmap_a5e99f850cd469e7d420d8a3568af11c4cdb6db9 };
ufc_finite_element* finite_elements_form_fb78e22a9a6073a61b5fb762f339e95a5b634838[3] = { &element_a5e99f850cd469e7d420d8a3568af11c4cdb6db9, &element_a5e99f850cd469e7d420d8a3568af11c4cdb6db9, &element_a5e99f850cd469e7d420d8a3568af11c4cdb6db9 };

// Return a list of the coefficient names.
const char** coefficient_name_form_fb78e22a9a6073a61b5fb762f339e95a5b634838(void)
{
static const char* names[2] = { "v_n", "g" };
return names;
}

// Return a list of the constant names.
const char** constant_name_form_fb78e22a9a6073a61b5fb762f339e95a5b634838(void)
{
static const char* names[1] = { "c0" };
return names;
}

int* integral_ids_form_fb78e22a9a6073a61b5fb762f339e95a5b634838(ufc_integral_type integral_type)
{
static int integral_ids_exterior_facet_form_fb78e22a9a6073a61b5fb762f339e95a5b634838[2] = { 1, 2 };
switch (integral_type)
{
case exterior_facet:
    return integral_ids_exterior_facet_form_fb78e22a9a6073a61b5fb762f339e95a5b634838;
default:
    return NULL;
}
}

int num_integrals_form_fb78e22a9a6073a61b5fb762f339e95a5b634838(ufc_integral_type integral_type)
{
switch (integral_type)
{
case cell:
    return 0;
case interior_facet:
    return 0;
case exterior_facet:
    return 2;
default:
    return 0;
}
}

ufc_integral** integrals_form_fb78e22a9a6073a61b5fb762f339e95a5b634838(ufc_integral_type integral_type)
{
static ufc_integral* integrals_exterior_facet_form_fb78e22a9a6073a61b5fb762f339e95a5b634838[2] = { &integral_4be71c5d2400b36f7fc7742798968f463c6b32c1, &integral_34c5363dbbbf18f54bd4da429b90a70aeb429e7f };
switch (integral_type)
{
case exterior_facet:
    return integrals_exterior_facet_form_fb78e22a9a6073a61b5fb762f339e95a5b634838;
default:
    return NULL;
}
}

ufc_form form_fb78e22a9a6073a61b5fb762f339e95a5b634838 =
{

  .signature = "ddd1d224d3cb03f8e989329b564257253f03a65cf395ab38ad0b549a1629282e532032ffc5a3321220281db46757258a4178a0c0ac1f22d9b8d19779e970a4fd",
  .rank = 1,
  .num_coefficients = 2,
  .num_constants = 1,
  .original_coefficient_position = original_coefficient_position_form_fb78e22a9a6073a61b5fb762f339e95a5b634838,

  .coefficient_name_map = coefficient_name_form_fb78e22a9a6073a61b5fb762f339e95a5b634838,
  .constant_name_map = constant_name_form_fb78e22a9a6073a61b5fb762f339e95a5b634838,

  .finite_elements = finite_elements_form_fb78e22a9a6073a61b5fb762f339e95a5b634838,
  .dofmaps = dofmaps_form_fb78e22a9a6073a61b5fb762f339e95a5b634838,

  .integral_ids = integral_ids_form_fb78e22a9a6073a61b5fb762f339e95a5b634838,
  .num_integrals = num_integrals_form_fb78e22a9a6073a61b5fb762f339e95a5b634838,

  .integrals = integrals_form_fb78e22a9a6073a61b5fb762f339e95a5b634838
};

// Alias name
ufc_form* form_forms_L = &form_fb78e22a9a6073a61b5fb762f339e95a5b634838;

ufc_function_space* functionspace_form_forms_L(const char* function_name)
{
static ufc_function_space functionspace_v =
{
.finite_element = &element_a5e99f850cd469e7d420d8a3568af11c4cdb6db9,
.dofmap = &dofmap_a5e99f850cd469e7d420d8a3568af11c4cdb6db9,
.geometry_family = "Q",
.geometry_degree = 1
};
static ufc_function_space functionspace_v_n =
{
.finite_element = &element_a5e99f850cd469e7d420d8a3568af11c4cdb6db9,
.dofmap = &dofmap_a5e99f850cd469e7d420d8a3568af11c4cdb6db9,
.geometry_family = "Q",
.geometry_degree = 1
};
static ufc_function_space functionspace_g =
{
.finite_element = &element_a5e99f850cd469e7d420d8a3568af11c4cdb6db9,
.dofmap = &dofmap_a5e99f850cd469e7d420d8a3568af11c4cdb6db9,
.geometry_family = "Q",
.geometry_degree = 1
};
if (strcmp(function_name, "v") == 0)
    return &functionspace_v;
else if (strcmp(function_name, "v_n") == 0)
    return &functionspace_v_n;
else if (strcmp(function_name, "g") == 0)
    return &functionspace_g;
return NULL;

}

// End of code for form form_fb78e22a9a6073a61b5fb762f339e95a5b634838
