// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['forms.ufl'],
//   'verbosity': 30,
//   'visualise': False}


typedef double ufc_scalar_t;
#include <math.h>
#include <stdalign.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <ufc.h>

// Code for element element_f5ef358ccd95b77d22896c7683f90fc4e72cc7b3





ufc_finite_element element_f5ef358ccd95b77d22896c7683f90fc4e72cc7b3 =
{
  .signature = "FiniteElement('Lagrange', interval, 1)",
  .cell_shape = interval,
  .element_type = ufc_basix_element,
  .topological_dimension = 1,
  .geometric_dimension = 1,
  .space_dimension = 2,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 1,
  .block_size = 1,
  .family = "Lagrange",
  .basix_family = 1,
  .basix_cell = 1,
  .discontinuous = false,
  .lagrange_variant = 0,
  .num_sub_elements = 0,
  .sub_elements = NULL
};

// End of code for element element_f5ef358ccd95b77d22896c7683f90fc4e72cc7b3

// Code for element element_187bcdff29370c654e431a7ecd92308d2dee849c

int value_shape_element_187bcdff29370c654e431a7ecd92308d2dee849c[1] = { 1 };
int reference_value_shape_element_187bcdff29370c654e431a7ecd92308d2dee849c[1] = { 1 };
ufc_finite_element* sub_elements_element_187bcdff29370c654e431a7ecd92308d2dee849c[1] = { &element_f5ef358ccd95b77d22896c7683f90fc4e72cc7b3 };

ufc_finite_element element_187bcdff29370c654e431a7ecd92308d2dee849c =
{
  .signature = "VectorElement(FiniteElement('Lagrange', interval, 1), dim=1)",
  .cell_shape = interval,
  .element_type = ufc_blocked_element,
  .topological_dimension = 1,
  .geometric_dimension = 1,
  .space_dimension = 2,
  .value_rank = 1,
  .value_shape = value_shape_element_187bcdff29370c654e431a7ecd92308d2dee849c,
  .value_size = 1,
  .reference_value_rank = 1,
  .reference_value_shape = reference_value_shape_element_187bcdff29370c654e431a7ecd92308d2dee849c,
  .reference_value_size = 1,
  .degree = 1,
  .block_size = 1,
  .family = "Lagrange",
  .basix_family = 1,
  .basix_cell = 1,
  .discontinuous = false,
  .lagrange_variant = 0,
  .num_sub_elements = 1,
  .sub_elements = sub_elements_element_187bcdff29370c654e431a7ecd92308d2dee849c
};

// End of code for element element_187bcdff29370c654e431a7ecd92308d2dee849c

// Code for element element_fd6a39ff124781dbabdc3a3e27acaffb204bf246





ufc_finite_element element_fd6a39ff124781dbabdc3a3e27acaffb204bf246 =
{
  .signature = "FiniteElement('Lagrange', interval, 4, variant='gll')",
  .cell_shape = interval,
  .element_type = ufc_basix_element,
  .topological_dimension = 1,
  .geometric_dimension = 1,
  .space_dimension = 5,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 4,
  .block_size = 1,
  .family = "Lagrange",
  .basix_family = 1,
  .basix_cell = 1,
  .discontinuous = false,
  .lagrange_variant = 1,
  .num_sub_elements = 0,
  .sub_elements = NULL
};

// End of code for element element_fd6a39ff124781dbabdc3a3e27acaffb204bf246

// Code for dofmap dofmap_f5ef358ccd95b77d22896c7683f90fc4e72cc7b3



void tabulate_entity_dofs_dofmap_f5ef358ccd95b77d22896c7683f90fc4e72cc7b3(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    }
    break;
}
}

void tabulate_entity_closure_dofs_dofmap_f5ef358ccd95b77d22896c7683f90fc4e72cc7b3(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    }
    break;
case 1:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        dofs[1] = 1;
        break;
    }
    break;
}
}

int num_entity_dofs_dofmap_f5ef358ccd95b77d22896c7683f90fc4e72cc7b3[4] = { 1, 0, 0, 0 };

int num_entity_closure_dofs_dofmap_f5ef358ccd95b77d22896c7683f90fc4e72cc7b3[4] = { 1, 2, 0, 0 };

ufc_dofmap dofmap_f5ef358ccd95b77d22896c7683f90fc4e72cc7b3 =
{
  .signature = "FFCx dofmap for FiniteElement('Lagrange', interval, 1)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 2,
  .block_size = 1,
  .num_entity_dofs = num_entity_dofs_dofmap_f5ef358ccd95b77d22896c7683f90fc4e72cc7b3,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_f5ef358ccd95b77d22896c7683f90fc4e72cc7b3,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_f5ef358ccd95b77d22896c7683f90fc4e72cc7b3,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_f5ef358ccd95b77d22896c7683f90fc4e72cc7b3,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_f5ef358ccd95b77d22896c7683f90fc4e72cc7b3

// Code for dofmap dofmap_187bcdff29370c654e431a7ecd92308d2dee849c

ufc_dofmap* sub_dofmaps_dofmap_187bcdff29370c654e431a7ecd92308d2dee849c[1] = { &dofmap_f5ef358ccd95b77d22896c7683f90fc4e72cc7b3 };

void tabulate_entity_dofs_dofmap_187bcdff29370c654e431a7ecd92308d2dee849c(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    }
    break;
}
}

void tabulate_entity_closure_dofs_dofmap_187bcdff29370c654e431a7ecd92308d2dee849c(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    }
    break;
case 1:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        dofs[1] = 1;
        break;
    }
    break;
}
}

int num_entity_dofs_dofmap_187bcdff29370c654e431a7ecd92308d2dee849c[4] = { 1, 0, 0, 0 };

int num_entity_closure_dofs_dofmap_187bcdff29370c654e431a7ecd92308d2dee849c[4] = { 1, 2, 0, 0 };

ufc_dofmap dofmap_187bcdff29370c654e431a7ecd92308d2dee849c =
{
  .signature = "FFCx dofmap for VectorElement(FiniteElement('Lagrange', interval, 1), dim=1)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 2,
  .block_size = 1,
  .num_entity_dofs = num_entity_dofs_dofmap_187bcdff29370c654e431a7ecd92308d2dee849c,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_187bcdff29370c654e431a7ecd92308d2dee849c,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_187bcdff29370c654e431a7ecd92308d2dee849c,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_187bcdff29370c654e431a7ecd92308d2dee849c,
  .num_sub_dofmaps = 1,
  .sub_dofmaps = sub_dofmaps_dofmap_187bcdff29370c654e431a7ecd92308d2dee849c
};

// End of code for dofmap dofmap_187bcdff29370c654e431a7ecd92308d2dee849c

// Code for dofmap dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246



void tabulate_entity_dofs_dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    }
    break;
case 1:
    switch (i)
    {
    case 0:
        dofs[0] = 2;
        dofs[1] = 3;
        dofs[2] = 4;
        break;
    }
    break;
}
}

void tabulate_entity_closure_dofs_dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    }
    break;
case 1:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        dofs[1] = 1;
        dofs[2] = 2;
        dofs[3] = 3;
        dofs[4] = 4;
        break;
    }
    break;
}
}

int num_entity_dofs_dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246[4] = { 1, 3, 0, 0 };

int num_entity_closure_dofs_dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246[4] = { 1, 5, 0, 0 };

ufc_dofmap dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246 =
{
  .signature = "FFCx dofmap for FiniteElement('Lagrange', interval, 4, variant='gll')",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 5,
  .block_size = 1,
  .num_entity_dofs = num_entity_dofs_dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246

// Code for integral integral_bca9f6a17d6de0ff0891d44d00c91872886cd5d0

void tabulate_tensor_integral_bca9f6a17d6de0ff0891d44d00c91872886cd5d0(ufc_scalar_t* restrict A,
                                    const ufc_scalar_t* restrict w,
                                    const ufc_scalar_t* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
    // Quadrature rules
    static const double weights_ba5[5] = { 0.05000000000000004, 0.2722222222222223, 0.3555555555555555, 0.272222222222222, 0.05000000000000004 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [permutation][entities][points][dofs]
    static const double FE1_C0_D1_Qba5[1][1][1][2] = { { { { -1.0, 1.0 } } } };
    static const double FE3_C0_Qba5[1][1][5][5] =
        { { { { 1.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 1.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 1.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 1.0 },
              { 0.0, 1.0, 0.0, 0.0, 0.0 } } } };
    // Quadrature loop independent computations for quadrature rule ba5
    const double J_c0 = coordinate_dofs[0] * FE1_C0_D1_Qba5[0][0][0][0] + coordinate_dofs[3] * FE1_C0_D1_Qba5[0][0][0][1];
    ufc_scalar_t sp_ba5[1];
    sp_ba5[0] = fabs(J_c0);
    for (int iq = 0; iq < 5; ++iq)
    {
        // Quadrature loop body setup for quadrature rule ba5
        // Varying computations for quadrature rule ba5
        ufc_scalar_t w0 = 0.0;
        for (int ic = 0; ic < 5; ++ic)
            w0 += w[ic] * FE3_C0_Qba5[0][0][iq][ic];
        ufc_scalar_t sv_ba5[1];
        sv_ba5[0] = sp_ba5[0] * w0;
        const ufc_scalar_t fw0 = sv_ba5[0] * weights_ba5[iq];
        for (int i = 0; i < 5; ++i)
            A[i] += fw0 * FE3_C0_Qba5[0][0][iq][i];
    }
}

bool enabled_coefficients_integral_bca9f6a17d6de0ff0891d44d00c91872886cd5d0[1] = { false };

ufc_integral integral_bca9f6a17d6de0ff0891d44d00c91872886cd5d0 =
{
  .enabled_coefficients = enabled_coefficients_integral_bca9f6a17d6de0ff0891d44d00c91872886cd5d0,
  .tabulate_tensor = tabulate_tensor_integral_bca9f6a17d6de0ff0891d44d00c91872886cd5d0,
  .needs_facet_permutations = false,
};

// End of code for integral integral_bca9f6a17d6de0ff0891d44d00c91872886cd5d0

// Code for integral integral_ad05401d3a720442671f50cf4be873dd28528a55

void tabulate_tensor_integral_ad05401d3a720442671f50cf4be873dd28528a55(ufc_scalar_t* restrict A,
                                    const ufc_scalar_t* restrict w,
                                    const ufc_scalar_t* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
    // Quadrature rules
    static const double weights_ba5[5] = { 0.05000000000000004, 0.2722222222222223, 0.3555555555555555, 0.272222222222222, 0.05000000000000004 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [permutation][entities][points][dofs]
    static const double FE1_C0_D1_Qba5[1][1][1][2] = { { { { -1.0, 1.0 } } } };
    static const double FE3_C0_D1_Qba5[1][1][5][5] =
        { { { { -9.999999999999995, -1.0, 13.51300497744847, -5.333333333333326, 2.82032835588485 },
              { -2.481980506061965, 0.5180194939380344, 0.0, 3.491486243775878, -1.527525231651946 },
              { 0.7499999999999997, -0.75, -2.673169155390907, 0.0, 2.673169155390906 },
              { -0.5180194939380343, 2.481980506061966, 1.527525231651947, -3.491486243775878, 0.0 },
              { 1.0, 10.0, -2.82032835588485, 5.333333333333331, -13.51300497744848 } } } };
    // Quadrature loop independent computations for quadrature rule ba5
    const double J_c0 = coordinate_dofs[0] * FE1_C0_D1_Qba5[0][0][0][0] + coordinate_dofs[3] * FE1_C0_D1_Qba5[0][0][0][1];
    ufc_scalar_t sp_ba5[1];
    sp_ba5[0] = fabs(J_c0);
    for (int iq = 0; iq < 5; ++iq)
    {
        // Quadrature loop body setup for quadrature rule ba5
        // Varying computations for quadrature rule ba5
        ufc_scalar_t w0_d1 = 0.0;
        for (int ic = 0; ic < 5; ++ic)
            w0_d1 += w[ic] * FE3_C0_D1_Qba5[0][0][iq][ic];
        ufc_scalar_t sv_ba5[4];
        sv_ba5[0] = w0_d1 * (1.0 / J_c0);
        sv_ba5[1] = sv_ba5[0] * (1.0 / J_c0);
        sv_ba5[2] = (-1 * sv_ba5[1]) * pow(c[0], 2);
        sv_ba5[3] = sv_ba5[2] * sp_ba5[0];
        const ufc_scalar_t fw0 = sv_ba5[3] * weights_ba5[iq];
        for (int i = 0; i < 5; ++i)
            A[i] += fw0 * FE3_C0_D1_Qba5[0][0][iq][i];
    }
}

bool enabled_coefficients_integral_ad05401d3a720442671f50cf4be873dd28528a55[3] = { false, false, false };

ufc_integral integral_ad05401d3a720442671f50cf4be873dd28528a55 =
{
  .enabled_coefficients = enabled_coefficients_integral_ad05401d3a720442671f50cf4be873dd28528a55,
  .tabulate_tensor = tabulate_tensor_integral_ad05401d3a720442671f50cf4be873dd28528a55,
  .needs_facet_permutations = false,
};

// End of code for integral integral_ad05401d3a720442671f50cf4be873dd28528a55

// Code for integral integral_27dfd05e838fbeaddafe5042ca6da04578ba8410

void tabulate_tensor_integral_27dfd05e838fbeaddafe5042ca6da04578ba8410(ufc_scalar_t* restrict A,
                                    const ufc_scalar_t* restrict w,
                                    const ufc_scalar_t* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
    // Quadrature rules
    static const double weights_709[1] = { 1 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [permutation][entities][points][dofs]
    static const double FE1_C0_F_Q709[1][2][1][5] =
        { { { { 1.0, 0.0, 0.0, 0.0, 0.0 } },
            { { 0.0, 1.0, 0.0, 0.0, 0.0 } } } };
    // Quadrature loop independent computations for quadrature rule 709
    ufc_scalar_t w2 = 0.0;
    for (int ic = 0; ic < 5; ++ic)
        w2 += w[10 + ic] * FE1_C0_F_Q709[0][entity_local_index[0]][0][ic];
    ufc_scalar_t sp_709[1];
    sp_709[0] = pow(c[0], 2) * w2;
    for (int iq = 0; iq < 1; ++iq)
    {
        const ufc_scalar_t fw0 = sp_709[0] * weights_709[iq];
        for (int i = 0; i < 5; ++i)
            A[i] += fw0 * FE1_C0_F_Q709[0][entity_local_index[0]][0][i];
    }
}

bool enabled_coefficients_integral_27dfd05e838fbeaddafe5042ca6da04578ba8410[3] = { false, false, false };

ufc_integral integral_27dfd05e838fbeaddafe5042ca6da04578ba8410 =
{
  .enabled_coefficients = enabled_coefficients_integral_27dfd05e838fbeaddafe5042ca6da04578ba8410,
  .tabulate_tensor = tabulate_tensor_integral_27dfd05e838fbeaddafe5042ca6da04578ba8410,
  .needs_facet_permutations = false,
};

// End of code for integral integral_27dfd05e838fbeaddafe5042ca6da04578ba8410

// Code for integral integral_0f63128090804a838575815ea7ade6038d1cced6

void tabulate_tensor_integral_0f63128090804a838575815ea7ade6038d1cced6(ufc_scalar_t* restrict A,
                                    const ufc_scalar_t* restrict w,
                                    const ufc_scalar_t* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
    // Quadrature rules
    static const double weights_709[1] = { 1 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [permutation][entities][points][dofs]
    static const double FE1_C0_F_Q709[1][2][1][5] =
        { { { { 1.0, 0.0, 0.0, 0.0, 0.0 } },
            { { 0.0, 1.0, 0.0, 0.0, 0.0 } } } };
    // Quadrature loop independent computations for quadrature rule 709
    ufc_scalar_t w1 = 0.0;
    for (int ic = 0; ic < 5; ++ic)
        w1 += w[5 + ic] * FE1_C0_F_Q709[0][entity_local_index[0]][0][ic];
    ufc_scalar_t sp_709[2];
    sp_709[0] = (1 / c[0]) * w1;
    sp_709[1] = (-1 * sp_709[0]) * pow(c[0], 2);
    for (int iq = 0; iq < 1; ++iq)
    {
        const ufc_scalar_t fw0 = sp_709[1] * weights_709[iq];
        for (int i = 0; i < 5; ++i)
            A[i] += fw0 * FE1_C0_F_Q709[0][entity_local_index[0]][0][i];
    }
}

bool enabled_coefficients_integral_0f63128090804a838575815ea7ade6038d1cced6[3] = { false, false, false };

ufc_integral integral_0f63128090804a838575815ea7ade6038d1cced6 =
{
  .enabled_coefficients = enabled_coefficients_integral_0f63128090804a838575815ea7ade6038d1cced6,
  .tabulate_tensor = tabulate_tensor_integral_0f63128090804a838575815ea7ade6038d1cced6,
  .needs_facet_permutations = false,
};

// End of code for integral integral_0f63128090804a838575815ea7ade6038d1cced6

// Code for form form_5faa0c8d1b7db5905d96695738090f52276ffba7

int original_coefficient_position_form_5faa0c8d1b7db5905d96695738090f52276ffba7[1] = { 0 };
ufc_dofmap* dofmaps_form_5faa0c8d1b7db5905d96695738090f52276ffba7[2] = { &dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246, &dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246 };
ufc_finite_element* finite_elements_form_5faa0c8d1b7db5905d96695738090f52276ffba7[2] = { &element_fd6a39ff124781dbabdc3a3e27acaffb204bf246, &element_fd6a39ff124781dbabdc3a3e27acaffb204bf246 };

// Return a list of the coefficient names.
const char** coefficient_name_form_5faa0c8d1b7db5905d96695738090f52276ffba7(void)
{
static const char* names[1] = { "u" };
return names;
}

// Return a list of the constant names.
const char** constant_name_form_5faa0c8d1b7db5905d96695738090f52276ffba7(void)
{
return NULL;
}

int* integral_ids_form_5faa0c8d1b7db5905d96695738090f52276ffba7(ufc_integral_type integral_type)
{
static int integral_ids_cell_form_5faa0c8d1b7db5905d96695738090f52276ffba7[1] = { -1 };
switch (integral_type)
{
case cell:
    return integral_ids_cell_form_5faa0c8d1b7db5905d96695738090f52276ffba7;
default:
    return NULL;
}
}

int num_integrals_form_5faa0c8d1b7db5905d96695738090f52276ffba7(ufc_integral_type integral_type)
{
switch (integral_type)
{
case cell:
    return 1;
case interior_facet:
    return 0;
case exterior_facet:
    return 0;
default:
    return 0;
}
}

ufc_integral** integrals_form_5faa0c8d1b7db5905d96695738090f52276ffba7(ufc_integral_type integral_type)
{
static ufc_integral* integrals_cell_form_5faa0c8d1b7db5905d96695738090f52276ffba7[1] = { &integral_bca9f6a17d6de0ff0891d44d00c91872886cd5d0 };
switch (integral_type)
{
case cell:
    return integrals_cell_form_5faa0c8d1b7db5905d96695738090f52276ffba7;
default:
    return NULL;
}
}

ufc_form form_5faa0c8d1b7db5905d96695738090f52276ffba7 =
{

  .signature = "90aa04d13fde393ef7418466be8c334cf9230e55606a4649da66d81d96530cd38ef400797f0f8026de75fc756c0df7249784f0ac027d8d634946c9544a2b162c",
  .rank = 1,
  .num_coefficients = 1,
  .num_constants = 0,
  .original_coefficient_position = original_coefficient_position_form_5faa0c8d1b7db5905d96695738090f52276ffba7,

  .coefficient_name_map = coefficient_name_form_5faa0c8d1b7db5905d96695738090f52276ffba7,
  .constant_name_map = constant_name_form_5faa0c8d1b7db5905d96695738090f52276ffba7,

  .finite_elements = finite_elements_form_5faa0c8d1b7db5905d96695738090f52276ffba7,
  .dofmaps = dofmaps_form_5faa0c8d1b7db5905d96695738090f52276ffba7,

  .integral_ids = integral_ids_form_5faa0c8d1b7db5905d96695738090f52276ffba7,
  .num_integrals = num_integrals_form_5faa0c8d1b7db5905d96695738090f52276ffba7,

  .integrals = integrals_form_5faa0c8d1b7db5905d96695738090f52276ffba7
};

// Alias name
ufc_form* form_forms_a = &form_5faa0c8d1b7db5905d96695738090f52276ffba7;

ufc_function_space* functionspace_form_forms_a(const char* function_name)
{
static ufc_function_space functionspace_v =
{
.finite_element = &element_fd6a39ff124781dbabdc3a3e27acaffb204bf246,
.dofmap = &dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
static ufc_function_space functionspace_u =
{
.finite_element = &element_fd6a39ff124781dbabdc3a3e27acaffb204bf246,
.dofmap = &dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
if (strcmp(function_name, "v") == 0)
    return &functionspace_v;
else if (strcmp(function_name, "u") == 0)
    return &functionspace_u;
return NULL;

}

// End of code for form form_5faa0c8d1b7db5905d96695738090f52276ffba7

// Code for form form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6

int original_coefficient_position_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6[3] = { 0, 1, 2 };
ufc_dofmap* dofmaps_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6[4] = { &dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246, &dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246, &dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246, &dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246 };
ufc_finite_element* finite_elements_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6[4] = { &element_fd6a39ff124781dbabdc3a3e27acaffb204bf246, &element_fd6a39ff124781dbabdc3a3e27acaffb204bf246, &element_fd6a39ff124781dbabdc3a3e27acaffb204bf246, &element_fd6a39ff124781dbabdc3a3e27acaffb204bf246 };

// Return a list of the coefficient names.
const char** coefficient_name_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6(void)
{
static const char* names[3] = { "u_n", "v_n", "g" };
return names;
}

// Return a list of the constant names.
const char** constant_name_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6(void)
{
static const char* names[1] = { "c0" };
return names;
}

int* integral_ids_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6(ufc_integral_type integral_type)
{
static int integral_ids_cell_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6[1] = { -1 };
static int integral_ids_exterior_facet_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6[2] = { 1, 2 };
switch (integral_type)
{
case cell:
    return integral_ids_cell_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6;
case exterior_facet:
    return integral_ids_exterior_facet_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6;
default:
    return NULL;
}
}

int num_integrals_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6(ufc_integral_type integral_type)
{
switch (integral_type)
{
case cell:
    return 1;
case interior_facet:
    return 0;
case exterior_facet:
    return 2;
default:
    return 0;
}
}

ufc_integral** integrals_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6(ufc_integral_type integral_type)
{
static ufc_integral* integrals_cell_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6[1] = { &integral_ad05401d3a720442671f50cf4be873dd28528a55 };
static ufc_integral* integrals_exterior_facet_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6[2] = { &integral_27dfd05e838fbeaddafe5042ca6da04578ba8410, &integral_0f63128090804a838575815ea7ade6038d1cced6 };
switch (integral_type)
{
case cell:
    return integrals_cell_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6;
case exterior_facet:
    return integrals_exterior_facet_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6;
default:
    return NULL;
}
}

ufc_form form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6 =
{

  .signature = "4c9064c8cfc96d95adea3b8c3ae92d4ed668e1cf41ad595aec647f28b9951476c8026ce7844b20066c52f453f4f621d783c4c2371ed63e33779e74075c01048d",
  .rank = 1,
  .num_coefficients = 3,
  .num_constants = 1,
  .original_coefficient_position = original_coefficient_position_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6,

  .coefficient_name_map = coefficient_name_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6,
  .constant_name_map = constant_name_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6,

  .finite_elements = finite_elements_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6,
  .dofmaps = dofmaps_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6,

  .integral_ids = integral_ids_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6,
  .num_integrals = num_integrals_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6,

  .integrals = integrals_form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6
};

// Alias name
ufc_form* form_forms_L = &form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6;

ufc_function_space* functionspace_form_forms_L(const char* function_name)
{
static ufc_function_space functionspace_v =
{
.finite_element = &element_fd6a39ff124781dbabdc3a3e27acaffb204bf246,
.dofmap = &dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
static ufc_function_space functionspace_u_n =
{
.finite_element = &element_fd6a39ff124781dbabdc3a3e27acaffb204bf246,
.dofmap = &dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
static ufc_function_space functionspace_v_n =
{
.finite_element = &element_fd6a39ff124781dbabdc3a3e27acaffb204bf246,
.dofmap = &dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
static ufc_function_space functionspace_g =
{
.finite_element = &element_fd6a39ff124781dbabdc3a3e27acaffb204bf246,
.dofmap = &dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
if (strcmp(function_name, "v") == 0)
    return &functionspace_v;
else if (strcmp(function_name, "u_n") == 0)
    return &functionspace_u_n;
else if (strcmp(function_name, "v_n") == 0)
    return &functionspace_v_n;
else if (strcmp(function_name, "g") == 0)
    return &functionspace_g;
return NULL;

}

// End of code for form form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6
