// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['forms.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

typedef double ufc_scalar_t;
#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufc_finite_element element_f5ef358ccd95b77d22896c7683f90fc4e72cc7b3;

extern ufc_finite_element element_187bcdff29370c654e431a7ecd92308d2dee849c;

extern ufc_finite_element element_fd6a39ff124781dbabdc3a3e27acaffb204bf246;

extern ufc_dofmap dofmap_f5ef358ccd95b77d22896c7683f90fc4e72cc7b3;

extern ufc_dofmap dofmap_187bcdff29370c654e431a7ecd92308d2dee849c;

extern ufc_dofmap dofmap_fd6a39ff124781dbabdc3a3e27acaffb204bf246;

extern ufc_integral integral_bca9f6a17d6de0ff0891d44d00c91872886cd5d0;

extern ufc_integral integral_ad05401d3a720442671f50cf4be873dd28528a55;

extern ufc_integral integral_27dfd05e838fbeaddafe5042ca6da04578ba8410;

extern ufc_integral integral_0f63128090804a838575815ea7ade6038d1cced6;

extern ufc_form form_5faa0c8d1b7db5905d96695738090f52276ffba7;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_forms_a;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_forms_a(const char* function_name);

extern ufc_form form_cde89256424f4ce7eca89c6c39559e1c44d1d1e6;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_forms_L;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_forms_L(const char* function_name);

#ifdef __cplusplus
}
#endif
