// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['forms.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufc_finite_element element_0e38e3c5cc256e0fdffd1c92e71f8c34b307d320;

extern ufc_finite_element element_a6e3e0cd38b5fe106365a8578b981e54950d9f2b;

extern ufc_finite_element element_9d6ce2fe3901e74605eea98aa23296f9d9c28b32;

extern ufc_dofmap dofmap_0e38e3c5cc256e0fdffd1c92e71f8c34b307d320;

extern ufc_dofmap dofmap_a6e3e0cd38b5fe106365a8578b981e54950d9f2b;

extern ufc_dofmap dofmap_9d6ce2fe3901e74605eea98aa23296f9d9c28b32;

extern ufc_integral integral_2261fd1466ac8086ef8e820f1befa1619258203a;

extern ufc_integral integral_4ab04c6f5ad1a00004b7a9f14fb9cb75f3ac48f5;

extern ufc_integral integral_d22f65149ee144387d2df0a17e8b8526c81e2a84;

extern ufc_integral integral_c21d3faeabcdb54df05595399b4f226345160613;

extern ufc_form form_b4c9e49198c07576c957cd52ed6d3c87661ddee2;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_forms_a;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_forms_a(const char* function_name);

extern ufc_form form_51ecc1ee027f8b1430ff39f81f836d90311a5b0f;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_forms_L;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_forms_L(const char* function_name);

#ifdef __cplusplus
}
#endif
