// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.1.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['forms.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

typedef double ufc_scalar_t;
#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufc_finite_element element_a29d126eb90717624045bf76a7bca19a674fc30a;

extern ufc_finite_element element_35acbbe5850b55bb602c0449eb587b74f5113101;

extern ufc_finite_element element_4217e4b1355aadfd36a846e75c60d470e7489c16;

extern ufc_dofmap dofmap_a29d126eb90717624045bf76a7bca19a674fc30a;

extern ufc_dofmap dofmap_35acbbe5850b55bb602c0449eb587b74f5113101;

extern ufc_dofmap dofmap_4217e4b1355aadfd36a846e75c60d470e7489c16;

extern ufc_integral integral_669e3fc3087f8152202515d887257ac4c0292527;

extern ufc_integral integral_726e700505a5bc12a1829016bec8bbaa0e7e6ae9;

extern ufc_integral integral_45c3b62aceeaad03d4adca5455d0fdd067327b69;

extern ufc_integral integral_eed02f4aac2ce24cb8a40d57a81250294a744d24;

extern ufc_form form_4abcbf725a752e7726771f9c5202099eb33a6402;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_forms_a;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_forms_a(const char* function_name);

extern ufc_form form_681ed7f34aaa0d7234155a34df3a98f813b583d3;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_forms_L;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_forms_L(const char* function_name);

#ifdef __cplusplus
}
#endif
