// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['forms.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufc_finite_element element_ee7755fb9192d85e9bbabdfa958a19575d037fcb;

extern ufc_finite_element element_c7ad61b539c6dd97225dd4dda3c3916557532058;

extern ufc_finite_element element_a5e99f850cd469e7d420d8a3568af11c4cdb6db9;

extern ufc_dofmap dofmap_ee7755fb9192d85e9bbabdfa958a19575d037fcb;

extern ufc_dofmap dofmap_c7ad61b539c6dd97225dd4dda3c3916557532058;

extern ufc_dofmap dofmap_a5e99f850cd469e7d420d8a3568af11c4cdb6db9;

extern ufc_integral integral_6d26c914a317c6e52000e7b50580922f1467d519;

extern ufc_integral integral_abfe688ba503fe767c6e6f7b891c3b747df62e80;

extern ufc_integral integral_828d923733b508ad5b2a8cd8d58c1ca493e16e8d;

extern ufc_integral integral_eaad4b24164c3af836eac9019d33a649179d3309;

extern ufc_form form_d9f14a3dc23beb8fab85a7a8352019423f17be07;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_forms_a;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_forms_a(const char* function_name);

extern ufc_form form_1293ea5ac8636e257eb1529c310dccd2d9422b2e;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_forms_L;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_forms_L(const char* function_name);

#ifdef __cplusplus
}
#endif
