// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.3.0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['forms.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

typedef double ufc_scalar_t;
#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufc_finite_element element_23c31b61d045664e6db105a2c9c3838bf3612ff9;

extern ufc_finite_element element_a9e8e7596b732d9bbfba031bddc043806ab90148;

extern ufc_finite_element element_9846521eb4e2336f35c4d59f548f622857f5d745;

extern ufc_dofmap dofmap_23c31b61d045664e6db105a2c9c3838bf3612ff9;

extern ufc_dofmap dofmap_a9e8e7596b732d9bbfba031bddc043806ab90148;

extern ufc_dofmap dofmap_9846521eb4e2336f35c4d59f548f622857f5d745;

extern ufc_integral integral_6a08d3cc04910ef90cc2b7425cc8af2e89a65a70;

extern ufc_integral integral_1c0f104b0a6aeaa3007978a0eda8821e28704c88;

extern ufc_integral integral_51c0f5ae86e8b8ecb9362acefeaefd959def338b;

extern ufc_integral integral_4abec0eccb06afd7e91e18216b7dfd1c1d36548b;

extern ufc_form form_c10b8da015cf0e810aa4211735045877aaeac115;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_forms_a;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_forms_a(const char* function_name);

extern ufc_form form_fb2f57bfe0d7914a95f75d4ab33514ea8511cfd1;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_forms_L;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_forms_L(const char* function_name);

#ifdef __cplusplus
}
#endif
