# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: HIFU CI

on:
  push:
    branches: 
      - "**"
  schedule:
    # '*' is a special character in YAML, so string must be quoted
    - cron: "0 1 * * *"

jobs:
  build:
    if: "!(contains(github.event.head_commit.message, '[ci skip]') || contains(github.event.head_commit.message, '[skip ci]'))"
    runs-on: ubuntu-20.04
    # container: dolfinx/dolfinx
    # steps:
    #   - uses: actions/checkout@v2
    container: dolfinx/dolfinx:nightly
    env:
      CC: gcc
      CXX: g++
      PETSC_ARCH: linux-gnu-real-32
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      OMPI_MCA_rmaps_base_oversubscribe: 1
      OMPI_MCA_plm: isolated
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      OMPI_MCA_mpi_yield_when_idle: 1
      OMPI_MCA_hwloc_base_binding_policy: none
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install hifusim package
      run: python3 -m pip -v install python/ --no-cache-dir

    - name: Flake8 checks
      run: |
        python3 -m flake8 python/tests/
        python3 -m flake8 python/src/hifusim/
    
    - name: Run tests
      run: |
        cd python/
        pytest tests/
